name: Build Bigo265 M3U8 (Native)

on:
  push:
    branches: [ "main" ]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Source Code
      uses: actions/checkout@v3

    - name: Siapkan Java (JDK 17)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Beri Izin Eksekusi Gradle
      run: chmod +x android/gradlew

    - name: Mulai Build APK
      run: |
        cd android
        ./gradlew test-app-maven-central:assembleDebug

    - name: Upload Hasil APK
      uses: actions/upload-artifact@v3
      with:
        name: Bigo265-Native-App
        path: android/test-app-maven-central/build/outputs/apk/debug/*.apk
